### ISSUE TITLE
How to use Fantome.Libraries.League?

### ISSUE THREAD

**Issue by KibaWolfOkami** [LoL-Fantome/Fantome.Libraries.League#96]
Hi. How to use Fantome.Libraries.League?  Can't figure it out, I don't understand this topic, I just need to convert scb to obj.

**Comment by Morilli** [comment]
This is a *library*, which means it will create a dll with usable functions instead of an executable. You could either use this dll in your own C# project and call its functions from there or use the existing [test](https://github.com/LoL-Fantome/Fantome.Libraries.League/tree/master/Fantome.Libraries.League.Tests) project and modify it to your needs.

**Comment by Crauzer** [comment]
As Morilli stated above, this is a *library*. That means its target userbase are developers that create tools.

The library itself can be used to convert between some file formats.

SCB/SCO -> OBJ will be implemented in [Obsidian](https://github.com/Crauzer/Obsidian) soon.
